# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cn", models.CharField(blank=True, max_length=255, verbose_name="cn")),
                ("issuer_cn", models.CharField(blank=True, max_length=255, verbose_name="Issuer cn")),
                ("organization", models.CharField(blank=True, max_length=255, verbose_name="Organization")),
                ("valid_from", models.DateTimeField(blank=True, null=True, verbose_name="Valid from")),
                ("valid_until", models.DateTimeField(blank=True, null=True, verbose_name="Valid until")),
                ("key_size", models.SmallIntegerField(verbose_name="Key size")),
                ("certificate", models.TextField(verbose_name="Certificate")),
            ],
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certificates",
            field=models.ManyToManyField(to="rr.Certificate"),
        ),
    ]
