# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0002_auto_20171229_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issuer_cn',
            new_name='issuer',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='sp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rr.ServiceProvider'),
            preserve_default=False,
        ),
    ]
