# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0003_auto_20180102_0736"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="created",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Entry end time"),
        ),
    ]
