# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 11:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0005_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AssertionConsumerService", "AssertionConsumerService"),
                            ("SingleLogoutService", "SingleLogoutService"),
                        ],
                        max_length=30,
                        verbose_name="Endpoint Type",
                    ),
                ),
                (
                    "binding",
                    models.CharField(
                        choices=[
                            ("HTTP-POST", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"),
                            ("HTTP-Redirect", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"),
                            ("HTTP-Artifact", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact"),
                        ],
                        max_length=30,
                        verbose_name="Endpoint Binding",
                    ),
                ),
                ("url", models.URLField(max_length=255, verbose_name="Endpoint URL")),
                ("created", models.DateTimeField(blank=True, null=True, verbose_name="Created at")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="Entry end time")),
                ("sp", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rr.ServiceProvider")),
            ],
        ),
    ]
