# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0006_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='encryption',
            field=models.BooleanField(default=False, verbose_name='Use for encryption'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signing',
            field=models.BooleanField(default=False, verbose_name='Use for signing'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Endpoint Index'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='binding',
            field=models.CharField(choices=[('urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'), ('urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'), ('urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact'), ('urn:oasis:names:tc:SAML:2.0:bindings:SOAP', 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP')], max_length=60, verbose_name='Endpoint Binding'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=models.CharField(choices=[('AssertionConsumerService', 'AssertionConsumerService'), ('SingleLogoutService', 'SingleLogoutService'), ('ArtifactResolutionService', 'ArtifactResolutionService')], max_length=30, verbose_name='Endpoint Type'),
        ),
    ]
