# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0010_auto_20180108_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="spattribute",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Entry end time"),
        ),
    ]
