# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0013_auto_20180112_1007"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spattribute",
            options={"ordering": ["attribute__friendlyname"]},
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="modified",
            field=models.BooleanField(default=True, verbose_name="Modified"),
        ),
    ]
