# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rr', '0014_auto_20180112_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keystore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40, verbose_name='Activation key')),
                ('valid_until', models.DateField(verbose_name='Valid until date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.ServiceProvider')),
            ],
        ),
    ]
