# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0015_keystore"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="validated",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validated on"),
        ),
        migrations.AddField(
            model_name="contact",
            name="validated",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validated on"),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="validated",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validated on"),
        ),
    ]
