# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0016_auto_20180115_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Login name')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Entry end time')),
            ],
        ),
        migrations.CreateModel(
            name='TestUserAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=511, verbose_name='Attribute value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.Attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.TestUser')),
            ],
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='history',
            field=models.IntegerField(blank=True, null=True, verbose_name='History key'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name_fi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service Name (Finnish)'),
        ),
        migrations.AddField(
            model_name='testuser',
            name='sp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.ServiceProvider'),
        ),
    ]
