# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0017_auto_20180119_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=511, null=True, verbose_name='Attribute value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.Attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='testuserattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='testuserattribute',
            name='user',
        ),
        migrations.AlterField(
            model_name='testuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.DeleteModel(
            name='TestUserAttribute',
        ),
        migrations.AddField(
            model_name='testuserdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.TestUser'),
        ),
    ]
