# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0019_auto_20180122_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validated on'),
        ),
    ]
