# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0020_auto_20180122_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='encyrpt_attribute_assertions',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='encyrpt_assertions',
            field=models.BooleanField(default=True, verbose_name='Encrypt SSO assertions'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sign_assertions',
            field=models.BooleanField(default=True, verbose_name='Sign SSO response messages'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sign_requests',
            field=models.BooleanField(default=False, verbose_name='Sign SSO request message'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='sign_responses',
            field=models.BooleanField(default=False, verbose_name='Sign SSO assertions within a message'),
        ),
    ]
