# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0022_auto_20180125_1036"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="discovery_service_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Discovery Service URL"),
        ),
    ]
