# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0024_serviceprovider_application_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='encyrpt_assertions',
            new_name='encrypt_assertions',
        ),
    ]
