# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0027_auto_20180219_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameidformat",
            name="public",
            field=models.BooleanField(default=True, verbose_name="Show in list"),
        ),
    ]
