# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0028_nameidformat_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='sign_assertions',
            field=models.BooleanField(default=False, verbose_name='Sign SSO assertions'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='sign_responses',
            field=models.BooleanField(default=True, verbose_name='Sign SSO responses'),
        ),
    ]
