# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0029_auto_20180220_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=78, null=True, verbose_name='Message title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Message body')),
            ],
        ),
    ]
