# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0030_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testuser",
            name="password",
            field=models.CharField(max_length=64, verbose_name="Password"),
        ),
    ]
