# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0032_auto_20180410_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="autoupdate_idp_metadata",
            field=models.BooleanField(default=False, verbose_name="SP updates IdP metadata automatically"),
        ),
    ]
