# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0033_auto_20180412_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='local_storage_groups',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of groups and group members.'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='local_storage_passwords',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of user passwords.'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='local_storage_passwords_info',
            field=models.TextField(blank=True, verbose_name='How is this service storing the saved passwords and why?'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='local_storage_users',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of users and their information.'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='server_names',
            field=models.CharField(blank=True, max_length=511, verbose_name='Server names (not IPs), separated with space'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_account',
            field=models.BooleanField(default=False, verbose_name='Does the service use a service account?'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_account_contact',
            field=models.TextField(blank=True, verbose_name='Email address and phone number for delivering the service account credentials.'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('saml', 'SAML / Shibboleth'), ('ldap', 'LDAP')], default='saml', max_length=10, verbose_name='Service type (SAML/LDAP)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='target_group',
            field=models.CharField(blank=True, choices=[('internet', 'Internet'), ('university', 'University of Helsinki users'), ('restricted', 'Restricted user group')], max_length=10, verbose_name='Target group for the service'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entity Id'),
        ),
    ]
