# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0033_auto_20180412_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='valid_for',
            field=models.ManyToManyField(blank=True, related_name='valid_for', to='rr.ServiceProvider', verbose_name='Valid for selected SPs'),
        ),
    ]
