# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0034_auto_20180413_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='public',
            new_name='public_saml',
        ),
    ]
