# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0034_testuser_valid_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="regex_test",
            field=models.CharField(blank=True, max_length=255, verbose_name="Regex text for attribute validation"),
        ),
        migrations.AddField(
            model_name="attribute",
            name="shib_env",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Shibboelth environmental variable for the attribute"
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="test_service",
            field=models.BooleanField(default=True, verbose_name="Show in Attribute test service"),
        ),
        migrations.AddField(
            model_name="attribute",
            name="test_service_required",
            field=models.BooleanField(default=False, verbose_name="Required attribute in test service"),
        ),
    ]
