# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0035_auto_20180629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Login name'),
        ),
        migrations.AlterField(
            model_name='testuserdata',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Login name'),
        ),
        migrations.AddIndex(
            model_name='testuserdata',
            index=models.Index(fields=['username'], name='rr_testuser_usernam_a96fae_idx'),
        ),
    ]
