# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0035_auto_20180413_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Attribute Group for LDAP'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='public_ldap',
            field=models.BooleanField(default=True, verbose_name='Show in LDAP attribute list'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='public_saml',
            field=models.BooleanField(default=True, verbose_name='Show in SAML attribute list'),
        ),
    ]
