# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0034_auto_20180413_1037_squashed_0039_auto_20180418_1217"),
        ("rr", "0036_auto_20180720_1436"),
    ]

    operations = []
