# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0036_auto_20180413_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Entry end time')),
                ('validated', models.DateTimeField(blank=True, null=True, verbose_name='Validated on')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr.ServiceProvider')),
            ],
        ),
    ]
