# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 08:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0037_merge_20180918_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='name_en',
            field=models.CharField(blank=True, max_length=140, validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Service Name (English)'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name_fi',
            field=models.CharField(blank=True, max_length=140, validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Service Name (Finnish)'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name_sv',
            field=models.CharField(blank=True, max_length=140, validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Service Name (Swedish)'),
        ),
    ]
