# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0038_auto_20180416_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='local_storage_groups',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of groups and group members'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='local_storage_passwords',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of user passwords'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='local_storage_users',
            field=models.BooleanField(default=False, verbose_name='Service stores a local copy of users and their information'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='server_names',
            field=models.TextField(blank=True, verbose_name='Server names (not IPs), one per line'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_account_contact',
            field=models.TextField(blank=True, verbose_name='Email address and phone number for delivering the service account credentials'),
        ),
    ]
