# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 10:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0039_serviceprovider_can_access_all_ldap_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=140,
                validators=[django.core.validators.MaxLengthValidator(70)],
                verbose_name="Service Name (English)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="name_fi",
            field=models.CharField(
                blank=True,
                max_length=140,
                validators=[django.core.validators.MaxLengthValidator(70)],
                verbose_name="Service Name (Finnish)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="name_sv",
            field=models.CharField(
                blank=True,
                max_length=140,
                validators=[django.core.validators.MaxLengthValidator(70)],
                verbose_name="Service Name (Swedish)",
            ),
        ),
    ]
