# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0042_auto_20190114_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='admin_require_manual_configuration',
            field=models.BooleanField(default=False, verbose_name='This service requires manual configuration'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='force_mfa',
            field=models.BooleanField(default=False, verbose_name='Require MFA authentication'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='force_nameidformat',
            field=models.BooleanField(default=False, verbose_name='Force use of specific nameIDFormat'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='force_sha1',
            field=models.BooleanField(default=False, verbose_name='Use SHA-1 as signature algorithm'),
        ),
    ]
