# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0043_auto_20190118_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="uses_ldapauth",
            field=models.BooleanField(default=False, verbose_name="Does the service use the LDAPAuth proxy?"),
        ),
    ]
