# Generated by Django 2.2.2 on 2019-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0047_oidc_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='scoped',
            field=models.BooleanField(default=False, verbose_name='Scoped attribute'),
        ),
    ]
