# Generated by Django 2.2.12 on 2020-06-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0052_serviceprovider_admin_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="endpoints", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="keystore",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="keys", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="redirecturi",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="redirecturis", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="testuser",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="testusers", to="rr.ServiceProvider"
            ),
        ),
        migrations.AlterField(
            model_name="testuserdata",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="rr.Attribute"
            ),
        ),
        migrations.AlterField(
            model_name="testuserdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="rr.TestUser"
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="sp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="usergroups", to="rr.ServiceProvider"
            ),
        ),
    ]
