# Generated by Django 2.2.24 on 2021-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rr", "0053_auto_20200612_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="users",
            field=models.IntegerField(null=True, verbose_name="Number of unique users"),
        ),
    ]
