# Generated by Django 4.2.16 on 2025-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rr", "0056_alter_spattribute_attribute_alter_spattribute_sp"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="saml_subject_identifier",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("any", "any"),
                    ("pairwise-id", "pairwise-id"),
                    ("subject-id", "subject-id"),
                ],
                default="none",
                max_length=11,
                verbose_name="Subject identifier",
            ),
        ),
    ]
